export const PLANETS_LOAD_PLANETS = 'PLANETS_LOAD_PLANETS';
export const PLANETS_GET_VIEWABLE_PLANET = 'PLANETS_GET_VIEWABLE_PLANET';
export const PLANETS_RESET_VIEWABLE_PLANET = 'PLANETS_RESET_VIEWABLE_PLANET';